# This file is used for the shared configuration between the production and the development environments 
version: "3" 
services:
  node-app:
    build: .  
    ports:
      - "3000:3000" 
    environment: 
      - PORT=3000
    depends_on:
      - mongo 
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eyeamkd
      - MONGO_INITDB_ROOT_PASSWORD=edo-okati
    volumes:
      - mongo-db:/data/db   
  redis:
    image: redis
volumes: 
  mongo-db:

    
