# This file is used for the shared configuration between the production and the development environments 
version: "3" 
services:
  node-app:
    build: .  
    ports:
      - "3000:3000" 
    environment: 
      - PORT=3000 
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eyeamkd
      - MONGO_INTIDB_ROOT_PASSWORD=edo-okati
    volumes:
      - mongo-db:/data/db
volumes: 
  mongo-db:

    
