version: "3" 
services:
  nginx:
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.config:/etc/nginx/conf.d/default.conf:ro
  node-app: 
    build: 
      context: .
      args:
        NODE_ENV: development 
    volumes:
      - ./:/app
      - /app/node_modules 
    environment:
      - NODE_ENV=development 
      - MONGO_USER=eyeamkd
      - MONGO_PASSWORD=edo-okati 
      - MONGO_PORT=27017 
      - SESSION_SECRET=somerandomstring    
    command: npm run dev 
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eyeamkd
      - MONGO_INITDB_ROOT_PASSWORD=edo-okati    
